# Customized by https://blog.devsense.com/2019/php-nginx-docker

version: '3.9'

services:

  nginx:
    image: nginx:1.23-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../web-app/:/var/www/html
      - ./logs/nginx:/var/log/nginx
    ports:
      - "8090:80"
      - "8091:443"
    networks:
      - internal

  php-basic:
    image: php:8.1-fpm-alpine
    container_name: php-basic
    restart: on-failure
    volumes:
      - ../web-app/:/var/www/html
      - ./logs/php.log:/var/log/fpm-php.www.log
    networks: 
      - internal

networks:
  internal:
    driver: bridge